[package]
name = "aetheros-kernel"
version = "1.1.0"
edition = "2021"

[dependencies]
# No external dependencies for microkernel core

[features]
default = []
ui = [] # Enable UI Engine

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
opt-level = "z"
lto = true
codegen-units = 1
